# Amfibieën

```{r}
sg <- "amfibieën"
```

## Overzicht monitoringsinspanning

```{r}

overzicht_bezoeken_tellers %>%
  filter(soortgroep == sg) %>%
  select(-soortgroep) %>%
  kable() %>%
  kable_styling("bordered", bootstrap_options = c("hover", "condensed")) %>%
  collapse_rows(1)

```

## Overzicht getelde aantallen {.tabset}

### Primaire soorten

```{r}

overzicht_aantallen_levensvorm_primair_wide %>%
  filter(soortgroep == sg) %>%
  select(-soortgroep, -soort_nl) %>%
  kable() %>%
  kable_styling(bootstrap_options = c("hover", "condensed")) %>%
    collapse_rows(c(1,2,3)) %>%
  scroll_box(width = "100%", height = "600px")
  
```

### Overige soorten

```{r}
overzicht_aantallen_levensvorm_overige_wide %>%
  mutate(soort_nl = ifelse(soort_wet == "Pelophylax esculenta synklepton",
                           "groene-kikker-complex", soort_nl)) %>%
  filter(soortgroep == sg) %>%
  select(-soortgroep) %>%
  kable() %>%
  kable_styling("bordered", bootstrap_options = c("hover", "condensed")) %>%
    collapse_rows(c(1,2,3)) %>%
  scroll_box(width = "100%", height = "600px")
```

## Verkenning getelde aantallen {.tabset}

### Boomkikker

```{r}
soort <- "Boomkikker"
stadium <- "adult"
```


```{r boomkikkerAdult, fig.cap= str_c("Evolutie getelde aantallen binnen telperiode: ", soort, " - ", stadium) , message=FALSE, warning= FALSE, fig.width= 8, fig.height= 3}

aantallen_soort_stadium <- aantallen_bezoek_levensvorm %>%
   filter(primaire_soort) %>%
   filter(meetnet == soort & levensstadium == stadium ) %>%
   mutate(doy_date = as.Date(doy, origin = "2016-01-01"))

max_soort_stadium <- max(aantallen_soort_stadium$aantal) * 1.2

 p <- aantallen_soort_stadium %>%
  ggplot(aes(x = doy_date, 
             y = aantal,
             group= locatie, 
             colour = locatie)) + 
  geom_point(alpha = 0.6) +  
 geom_line(linetype = 2,  alpha = 0.6, size = 0.4, colour = inbo.grijsblauw)  + 
  facet_grid(soort_stadium ~ jaar) +
  labs(x = "Datum bezoek", y = "Aantal getelde adulten") + 
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +
  ylim(0, max_soort_stadium) + 
  theme(legend.position = 'none', axis.text.x = element_text(angle = 90))
  p #ggplotly(p) 

 q <- aantallen_soort_stadium %>%
  ggplot(aes(x = doy_date, 
             y = aantal, 
 #            size = aantalSectiesGeteld, 
             colour = locatie)) + 
  geom_point(alpha = 0.6) + 
  geom_smooth(method = "gam", method.args = list(family = poisson),formula = y ~ s(x, bs = "cs", k = 5) , size = 0.4, colour = "blue") +
  facet_grid(soort_stadium ~ jaar) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +
   labs(x = "Datum bezoek", y = "Aantal getelde adulten") + 
  ylim(0, max_soort_stadium) + 
  theme(legend.position = 'none', axis.text.x = element_text(angle = 90)) 
 q #ggplotly(q)
 
```

```{r}
soort <- "Boomkikker"
stadium <- "larve"
```

```{r boomkikkerLarve, fig.cap= str_c("Evolutie getelde aantallen binnen telperiode: ", soort, " - ", stadium),  message=FALSE, warning= FALSE, fig.width= 8, fig.height= 3}

aantallen_soort_stadium <- aantallen_bezoek_levensvorm %>%
   filter(primaire_soort) %>%
   filter(meetnet == soort & levensstadium == stadium ) %>%
   mutate(doy_date = as.Date(doy, origin = "2016-01-01"))

max_soort_stadium <- max(aantallen_soort_stadium$aantal) * 1.2

 p <- aantallen_soort_stadium %>%
  ggplot(aes(x = doy_date, 
             y = aantal,
             group= locatie, 
             colour = locatie)) + 
  geom_point(alpha = 0.6) +  
 geom_line(linetype = 2,  alpha = 0.6, size = 0.4, colour = inbo.grijsblauw)  + 
  facet_grid(soort_stadium ~ jaar) +
  labs(x = "Datum bezoek", y = "Aantal getelde larven") + 
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +
  ylim(0, max_soort_stadium) + 
  theme(legend.position = 'none', axis.text.x = element_text(angle = 90))
  p #ggplotly(p) 

 q <- aantallen_soort_stadium %>%
  ggplot(aes(x = doy_date, 
             y = aantal, 
 #            size = aantalSectiesGeteld, 
             colour = locatie)) + 
  geom_point(alpha = 0.6) + 
  geom_smooth(method = "gam", method.args = list(family = poisson),formula = y ~ s(x, bs = "cs", k = 5) , size = 0.4, colour = "blue") +
  facet_grid(soort_stadium ~ jaar) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +
   labs(x = "Datum bezoek", y = "Aantal getelde larven") + 
  ylim(0, max_soort_stadium) + 
  theme(legend.position = 'none', axis.text.x = element_text(angle = 90)) 
 q #ggplotly(q)
 
```


```{r boomkikkerMean, fig.cap= str_c("Evolutie gemiddelde getelde aantallen per bezoek: ", soort), fig.height= 3, fig.width= 7}

aantallen_soort_stadium <- aantallen_bezoek_levensvorm %>%
   filter(primaire_soort) %>%
   filter(meetnet == soort) 

max_soort_stadium <- max(aantallen_soort_stadium$aantal) * 1.2

aantallen_soort_stadium %>%
  ggplot(aes(x= jaar, y = aantal)) +  
  #geom_point(alpha = 0.6, colour = inbo.grijs) +
  stat_summary(fun.data = "mean_cl_boot", colour = INBOred, size = 1, alpha = 0.8) +
  facet_wrap(~ soort_stadium, scale = "free_y") +
  labs(y = "Aantal getelde individuen", x = "Jaar") +
  theme(legend.position = "bottom") 

```


### Knoflookpad


```{r}
soort <- "Knoflookpad"
stadium <- "adult"
```

```{r knoflookpadAdult, fig.cap= str_c("Evolutie getelde aantallen binnen telperiode: ", soort, " - ", stadium), message=FALSE, warning= FALSE, fig.width= 8, fig.height= 3}

aantallen_soort_stadium <- aantallen_bezoek_levensvorm %>%
   filter(primaire_soort) %>%
   filter(meetnet == soort & levensstadium == stadium ) %>%
   mutate(doy_date = as.Date(doy, origin = "2016-01-01"))

max_soort_stadium <- max(aantallen_soort_stadium$aantal) * 1.2

 p <- aantallen_soort_stadium %>%
  ggplot(aes(x = doy_date, 
             y = aantal,
             group= locatie, 
             colour = locatie)) + 
  geom_point(alpha = 0.6) +  
 geom_line(linetype = 2,  alpha = 0.6, size = 0.4, colour = inbo.grijsblauw)  + 
  facet_grid(soort_stadium ~ jaar) +
  labs(x = "Datum bezoek", y = "Aantal getelde adulten") + 
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +
  ylim(0, max_soort_stadium) + 
  theme(legend.position = 'none', axis.text.x = element_text(angle = 90))
  p #ggplotly(p) 

 
```


```{r}
soort <- "Knoflookpad"
stadium <- "larve"

```


```{r knoflookpadLarve, fig.cap= str_c("Evolutie getelde aantallen binnen telperiode: ", soort, " - ", stadium), message=FALSE, warning= FALSE, fig.width= 3, fig.height= 3}

aantallen_soort_stadium <- aantallen_bezoek_levensvorm %>%
   filter(primaire_soort) %>%
   filter(meetnet == soort & levensstadium == stadium ) %>%
   mutate(doy_date = as.Date(doy, origin = "2016-01-01"))

max_soort_stadium <- max(aantallen_soort_stadium$aantal) * 1.2

 p <- aantallen_soort_stadium %>%
  ggplot(aes(x = doy_date, 
             y = aantal,
             group= locatie, 
             colour = locatie)) + 
  geom_point(alpha = 0.6) +  
 geom_line(linetype = 2,  alpha = 0.6, size = 0.4, colour = inbo.grijsblauw)  + 
  facet_grid(soort_stadium ~ jaar) +
  labs(x = "Datum bezoek", y = "Aantal getelde larven") + 
  ylim(0, max_soort_stadium) + 
  theme(legend.position = 'none', axis.text.x = element_text(angle = 90))
  p #ggplotly(p) 


 
```


```{r knoflookpadMean, fig.cap= str_c("Evolutie gemiddelde getelde aantallen per bezoek: ", soort), fig.height= 3, fig.width= 6}

aantallen_soort_stadium <- aantallen_bezoek_levensvorm %>%
   filter(primaire_soort) %>%
   filter(meetnet == soort) 

max_soort_stadium <- max(aantallen_soort_stadium$aantal) * 1.2

aantallen_soort_stadium %>%
  filter(levensstadium != "metamorf") %>%
  ggplot(aes(x= factor(jaar), y = aantal)) +  
  #geom_point(alpha = 0.6, colour = inbo.grijs) +
  stat_summary(fun.data = "mean_cl_boot", colour = INBOred, size = 1, alpha = 0.8) +
  facet_wrap(~ soort_stadium, scale = "free_y") +
  labs(y = "Aantal getelde individuen", x = "Jaar") +
  theme(legend.position = "bottom") 

```


### Rugstreeppad

```{r}
soort <- "Rugstreeppad"
stadium <- "adult"
```

```{r rugstreeppadAdult, fig.cap= str_c("Evolutie getelde aantallen binnen telperiode: ", soort, " - ", stadium),  message=FALSE, warning= FALSE, fig.width= 6, fig.height= 3}

soort <- "Rugstreeppad"
stadium <- "adult"

aantallen_soort_stadium <- aantallen_bezoek_levensvorm %>%
   filter(primaire_soort) %>%
   filter(meetnet == soort & levensstadium == stadium ) %>%
   mutate(doy_date = as.Date(doy, origin = "2016-01-01"))

max_soort_stadium <- max(aantallen_soort_stadium$aantal) * 1.2

 p <- aantallen_soort_stadium %>%
  ggplot(aes(x = doy_date, 
             y = aantal,
             group= locatie, 
             colour = locatie)) + 
  geom_point(alpha = 0.6) +  
 geom_line(linetype = 2,  alpha = 0.6, size = 0.4, colour = inbo.grijsblauw)  + 
  facet_grid(soort_stadium ~ jaar) +
  labs(x = "Datum bezoek", y = "Aantal getelde adulten") + 
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +
  ylim(0, max_soort_stadium) + 
  theme(legend.position = 'none', axis.text.x = element_text(angle = 90))
  p #ggplotly(p) 
  
   q <- aantallen_soort_stadium %>%
  ggplot(aes(x = doy_date, 
             y = aantal, 
 #            size = aantalSectiesGeteld, 
             colour = locatie)) + 
  geom_point(alpha = 0.6) + 
  geom_smooth(method = "gam", method.args = list(family = poisson),formula = y ~ s(x, bs = "cs", k = 5) , size = 0.4, colour = "blue") +
  facet_grid(soort_stadium ~ jaar) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +
   labs(x = "Datum bezoek", y = "Aantal getelde larven") + 
  ylim(0, max_soort_stadium) + 
  theme(legend.position = 'none', axis.text.x = element_text(angle = 90)) 
 q

 
```

```{r}
soort <- "Rugstreeppad"
stadium <- "juveniel"
```

```{r rugstreeppadJuveniel, fig.cap= str_c("Evolutie getelde aantallen binnen telperiode: ", soort, " - ", stadium),message=FALSE, warning= FALSE, fig.width= 6, fig.height= 3}

aantallen_soort_stadium <- aantallen_bezoek_levensvorm %>%
   filter(primaire_soort) %>%
   filter(meetnet == soort & levensstadium == stadium ) %>%
   mutate(doy_date = as.Date(doy, origin = "2016-01-01"))

max_soort_stadium <- max(aantallen_soort_stadium$aantal) * 1.2

 p <- aantallen_soort_stadium %>%
  ggplot(aes(x = doy_date, 
             y = aantal,
             group= locatie, 
             colour = locatie)) + 
  geom_point(alpha = 0.6) +  
 geom_line(linetype = 2,  alpha = 0.6, size = 0.4, colour = inbo.grijsblauw)  + 
  facet_grid(soort_stadium ~ jaar) +
  labs(x = "Datum bezoek", y = "Aantal getelde juvenielen") + 
  ylim(0, max_soort_stadium) + 
  theme(legend.position = 'none', axis.text.x = element_text(angle = 90))
  p #ggplotly(p) 


 
```

```{r}
soort <- "Rugstreeppad"
stadium <- "ei"
```

```{r rugstreeppadEi, fig.cap= str_c("Evolutie getelde aantallen binnen telperiode: ", soort, " - ", stadium),  message=FALSE, warning= FALSE, fig.width= 6, fig.height= 3}

aantallen_soort_stadium <- aantallen_bezoek_levensvorm %>%
   filter(primaire_soort) %>%
   filter(meetnet == soort & levensstadium == stadium ) %>%
   mutate(doy_date = as.Date(doy, origin = "2016-01-01"))

max_soort_stadium <- max(aantallen_soort_stadium$aantal) * 1.2

 p <- aantallen_soort_stadium %>%
  ggplot(aes(x = doy_date, 
             y = aantal,
             group= locatie, 
             colour = locatie)) + 
  geom_point(alpha = 0.6) +  
 geom_line(linetype = 2,  alpha = 0.6, size = 0.4, colour = inbo.grijsblauw)  + 
  facet_grid(soort_stadium ~ jaar) +
  labs(x = "Datum bezoek", y = "Aantal getelde eisnoeren") + 
  ylim(0, max_soort_stadium) + 
   scale_y_continuous(breaks = (c(0,1))) +
  theme(legend.position = 'none', axis.text.x = element_text(angle = 90))
  p #ggplotly(p) 


 
```


```{r}
soort <- "Rugstreeppad"
stadium <- "larve"
```


```{r rugstreeppadLarve, fig.cap= str_c("Evolutie getelde aantallen binnen telperiode: ", soort, " - ", stadium),  message=FALSE, warning= FALSE, fig.width= 6, fig.height= 3}

aantallen_soort_stadium <- aantallen_bezoek_levensvorm %>%
   filter(primaire_soort) %>%
   filter(meetnet == soort & levensstadium == stadium ) %>%
   mutate(doy_date = as.Date(doy, origin = "2016-01-01"))

max_soort_stadium <- max(aantallen_soort_stadium$aantal) * 1.2

 p <- aantallen_soort_stadium %>%
  ggplot(aes(x = doy_date, 
             y = aantal,
             group= locatie, 
             colour = locatie)) + 
  geom_point(alpha = 0.6) +  
 geom_line(linetype = 2,  alpha = 0.6, size = 0.4, colour = inbo.grijsblauw)  + 
  facet_grid(soort_stadium ~ jaar) +
  labs(x = "Datum bezoek", y = "Aantal getelde larven") + 
  ylim(0, max_soort_stadium) + 
  theme(legend.position = 'none', axis.text.x = element_text(angle = 90))
  p #ggplotly(p) 


 
```


```{r rugstreeppadMean, fig.cap= str_c("Evolutie gemiddelde getelde aantallen per bezoek: ", soort), fig.height= 5, fig.width= 6}

aantallen_soort_stadium <- aantallen_bezoek_levensvorm %>%
   filter(primaire_soort) %>%
   filter(meetnet == soort) 

max_soort_stadium <- max(aantallen_soort_stadium$aantal) * 1.2

aantallen_soort_stadium %>%
  filter(levensstadium != "metamorf") %>%
  ggplot(aes(x= factor(jaar), y = aantal)) +  
  #geom_point(alpha = 0.6, colour = inbo.grijs) +
  stat_summary(fun.data = "mean_cl_boot", colour = INBOred, size = 1, alpha = 0.8) +
  facet_wrap(~ soort_stadium, scale = "free_y") +
  labs(y = "Aantal getelde individuen", x = "Jaar") +
  theme(legend.position = "bottom") 

```


### Kamsalamander

```{r}
soort <- "Kamsalamander"
stadium <- "adult"
```

```{r kamsalamanderAdult, fig.cap= str_c("Evolutie getelde aantallen binnen telperiode: ", soort, " - ", stadium), message=FALSE, warning= FALSE, fig.width= 7, fig.height= 3}

aantallen_soort_stadium <- aantallen_bezoek_levensvorm %>%
   filter(primaire_soort) %>%
   filter(meetnet == soort & levensstadium == stadium ) %>%
   mutate(doy_date = as.Date(doy, origin = "2016-01-01"))

max_soort_stadium <- max(aantallen_soort_stadium$aantal) * 1.2

 p <- aantallen_soort_stadium %>%
  ggplot(aes(x = doy_date, 
             y = aantal,
             group= locatie, 
             colour = locatie)) + 
  geom_point(alpha = 0.6) +  
 geom_line(linetype = 2,  alpha = 0.6, size = 0.4, colour = inbo.grijsblauw)  + 
  facet_grid(soort_stadium ~ jaar) +
  labs(x = "Datum bezoek", y = "Aantal getelde adulten") + 
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +
  ylim(0, max_soort_stadium) + 
  theme(legend.position = 'none', axis.text.x = element_text(angle = 90))
  p #ggplotly(p) 

 q <- aantallen_soort_stadium %>%
  ggplot(aes(x = doy_date, 
             y = aantal, 
 #            size = aantalSectiesGeteld, 
             colour = locatie)) + 
  geom_point(alpha = 0.6) + 
  geom_smooth(method = "gam", method.args = list(family = poisson),formula = y ~ s(x, bs = "cs", k = 5) , size = 0.4, colour = "blue") +
  facet_grid(soort_stadium ~ jaar) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +
   labs(x = "Datum bezoek", y = "Aantal getelde adulten") + 
  ylim(0, max_soort_stadium) + 
  theme(legend.position = 'none', axis.text.x = element_text(angle = 90)) 
 q #ggplotly(q)
 
```

```{r}

soort <- "Kamsalamander"
stadium <- "larve"

```


```{r kamsalamanderLarve, fig.cap= str_c("Evolutie getelde aantallen binnen telperiode: ", soort, " - ", stadium),  message=FALSE, warning= FALSE, fig.width= 7, fig.height= 3}

aantallen_soort_stadium <- aantallen_bezoek_levensvorm %>%
   filter(primaire_soort) %>%
   filter(meetnet == soort & levensstadium == stadium ) %>%
   mutate(doy_date = as.Date(doy, origin = "2016-01-01"))

max_soort_stadium <- max(aantallen_soort_stadium$aantal) * 1.2

 p <- aantallen_soort_stadium %>%
  ggplot(aes(x = doy_date, 
             y = aantal,
             group= locatie, 
             colour = locatie)) + 
  geom_point(alpha = 0.6) +  
 geom_line(linetype = 2,  alpha = 0.6, size = 0.4, colour = inbo.grijsblauw)  + 
  facet_grid(soort_stadium ~ jaar) +
  labs(x = "Datum bezoek", y = "Aantal getelde adulten") + 
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +
  ylim(0, max_soort_stadium) + 
  theme(legend.position = 'none', axis.text.x = element_text(angle = 90))
  p #ggplotly(p) 


 
```

```{r kamsalamanderMean, fig.cap= str_c("Evolutie gemiddelde getelde aantallen per bezoek: ", soort), fig.height= 5, fig.width= 6}

aantallen_soort_stadium <- aantallen_bezoek_levensvorm %>%
   filter(primaire_soort) %>%
   filter(meetnet == soort) 

max_soort_stadium <- max(aantallen_soort_stadium$aantal) * 1.2

aantallen_soort_stadium %>%
  ggplot(aes(x= factor(jaar), y = aantal)) +  
  #geom_point(alpha = 0.6, colour = inbo.grijs) +
  stat_summary(fun.data = "mean_cl_boot", colour = INBOred, size = 1, alpha = 0.8) +
  facet_wrap(~ soort_stadium, scale = "free_y") +
  labs(y = "Aantal getelde individuen", x = "Jaar") +
  theme(legend.position = "bottom") 

```


### Vuursalamander


```{r}
soort <- "Vuursalamander"
stadium <- "post-metamorf"

```

```{r vuursalamanderPostmetamorf, fig.cap= str_c("Evolutie getelde aantallen binnen telperiode: ", soort, " - ", stadium), message=FALSE, warning= FALSE, fig.width= 8, fig.height= 3}


aantallen_soort_stadium <- aantallen_bezoek_levensvorm %>%
   filter(primaire_soort) %>%
  filter(doy > 150) %>%
   filter(meetnet == soort & levensstadium == stadium ) %>%
   mutate(doy_date = as.Date(doy, origin = "2016-01-01"))

max_soort_stadium <- max(aantallen_soort_stadium$aantal) * 1.2

 p <- aantallen_soort_stadium %>%
  ggplot(aes(x = doy_date, 
             y = aantal,
             group= locatie, 
             colour = locatie)) + 
  geom_point(alpha = 0.6) +  
 geom_line(linetype = 2,  alpha = 0.6, size = 0.4, colour = inbo.grijsblauw)  + 
  facet_grid(soort_stadium ~ jaar) +
  labs(x = "Datum bezoek", y = "Aantal getelde post-metamorfen") + 
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +
  ylim(0, max_soort_stadium) + 
  theme(legend.position = 'none', axis.text.x = element_text(angle = 90))
  p #ggplotly(p) 

 q <- aantallen_soort_stadium %>%
  ggplot(aes(x = doy_date, 
             y = aantal, 
 #            size = aantalSectiesGeteld, 
             colour = locatie)) + 
  geom_point(alpha = 0.6) + 
  geom_smooth(method = "gam", method.args = list(family = poisson),formula = y ~ s(x, bs = "cs", k = 5) , size = 0.4, colour = "blue") +
  facet_grid(soort_stadium ~ jaar) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +
   labs(x = "Datum bezoek", y = "Aantal getelde adulten") + 
  ylim(0, max_soort_stadium) + 
  theme(legend.position = 'none', axis.text.x = element_text(angle = 90)) 
 q #ggplotly(q)
 
```


```{r vuursalamanderMean, fig.cap= str_c("Evolutie gemiddelde getelde aantallen per bezoek: ", soort), fig.height= 4, fig.width= 4}


aantallen_soort_stadium <- aantallen_bezoek_levensvorm %>%
   filter(primaire_soort) %>%
   filter(meetnet == soort) 

max_soort_stadium <- max(aantallen_soort_stadium$aantal) * 1.2

aantallen_soort_stadium %>%
  ggplot(aes(x= jaar, y = aantal)) +  
  #geom_point(alpha = 0.6, colour = inbo.grijs) +
  stat_summary(fun.data = "mean_cl_boot", colour = INBOred, size = 1, alpha = 0.8) +
  facet_wrap(~ soort_stadium, scale = "free_y") +
  labs(y = "Aantal getelde individuen", x = "Jaar") +
  theme(legend.position = "bottom") 

```


