# Kevers, spinnen en sprinkhanen

```{r}
sg <- "overige"
```

## Overzicht monitoringsinspanning

```{r}

overzicht_bezoeken_tellers %>%
  filter(soortgroep == sg) %>%
  filter(meetnet != "Vliegend hert - inhaalslag (afgerond)") %>%
  select(-soortgroep) %>%
  kable() %>%
  kable_styling("bordered", bootstrap_options = c("hover", "condensed")) %>%
  collapse_rows(1)

```

## Overzicht getelde aantallen {.tabset}

### Meetnetsoorten

```{r}

overzicht_aantallen_levensstadium_primair_wide %>%
  filter(soortgroep == sg) %>%
  filter(meetnet != "Vliegend hert - inhaalslag (afgerond)") %>%
  select(-soortgroep, -soort_nl, "Nederlandse naam" = meetnet, "wetenschappelijke naam" = soort_wet) %>%
  kable() %>%
  kable_styling(bootstrap_options = c("hover", "condensed")) %>%
    column_spec(2, italic = TRUE) %>%
    collapse_rows(c(1,2,3), target = 1) %>%
  scroll_box(width = "100%", height = "600px")
  
```

### Overige soorten

```{r}
overzicht_aantallen_levensstadium_overige_wide %>%
  mutate(soort_nl = ifelse(soort_wet == "Pelophylax esculenta synklepton",
                           "groene-kikker-complex", soort_nl)) %>%
  filter(soortgroep == sg) %>%
  select(-soortgroep, "Nederlandse naam" = soort_nl, "wetenschappelijke naam" = soort_wet, -"2016", -"2017", -"2018", -"2019", -levensstadium) %>%
  kable() %>%
  kable_styling("bordered", bootstrap_options = c("hover", "condensed")) %>%
    column_spec(2, italic = TRUE) %>%
    collapse_rows(c(1,2,3), target = 1) %>%
  scroll_box(width = "100%", height = "600px")
```

## Verkenning getelde aantallen {.tabset}

### Lentevuurspin

```{r}
soort <- "Lentevuurspin"

```

```{r Lentevuurspingemiddeld, fig.cap= str_c("Evolutie gemiddelde getelde aantallen per bezoek: ", soort), fig.height= 3, fig.width= 4}
aantallen_soort <- aantallen_bezoek_totaal %>%
   filter(primaire_soort) %>%
   filter(meetnet == soort ) 

aantallen_soort %>%
  ggplot(aes(x= jaar, y = aantal)) +  
  #geom_point(alpha = 0.6, colour = inbo.grijs) +
  stat_summary(fun.data = "mean_cl_boot", colour = inbo_rood, size = 1, alpha = 0.8) +
  facet_wrap(~ soort_nl, scale = "free_y") +
  labs(y = "Aantal getelde individuen", x = "Jaar") +
  theme(legend.position = "bottom") 

```

```{r Lentevuurspin, fig.cap= str_c("Evolutie getelde aantallen per locatie: ", soort) , message=FALSE, warning= FALSE, fig.width= 5, fig.height= 3}



max_soort <- max(aantallen_soort$aantal) * 1.2

 p <- aantallen_soort %>%
  ggplot(aes(x = jaar, 
             y = aantal,
             group= locatie, 
             colour = locatie)) + 
  geom_point(alpha = 0.6) +  
 geom_line(linetype = 2,  alpha = 0.6, size = 0.4, colour = inbo_grijsblauw)  + 
 # facet_grid(soort_nl ~ jaar) +
  labs(x = "Jaar", y = "Aantal getelde individuen") + 
  ylim(0, max_soort) + 
  theme(legend.position = 'none', axis.text.x = element_text(angle = 90))
  p #ggplotly(p) 

 
```

### Schavertje

```{r}
soort <- "Schavertje"

```

```{r Schavertjegemiddeld, fig.cap= str_c("Evolutie gemiddelde getelde aantallen per bezoek: ", soort), fig.height= 3, fig.width= 3}

aantallen_soort <- aantallen_bezoek_totaal %>%
   filter(primaire_soort) %>%
   filter(meetnet == soort ) %>%
   mutate(doy_date = as.Date(doy, origin = "2016-01-01"))

aantallen_soort %>%
  ggplot(aes(x= jaar, y = aantal)) +  
  #geom_point(alpha = 0.6, colour = inbo.grijs) +
  stat_summary(fun.data = "mean_cl_boot", colour = inbo_rood, size = 1, alpha = 0.8) +
  facet_wrap(~ soort_nl, scale = "free_y") +
  labs(y = "Aantal getelde individuen", x = "Jaar") +
  theme(legend.position = "bottom") 

```

```{r Schavertje, fig.cap= str_c("Evolutie getelde individuen binnen telperiode: ", soort) , message=FALSE, warning= FALSE, fig.width= 4, fig.height= 3}



max_soort <- max(aantallen_soort$aantal) * 1.2

 p <- aantallen_soort %>%
  ggplot(aes(x = doy_date, 
             y = aantal,
             group= locatie, 
             colour = locatie)) + 
  geom_point(alpha = 0.6) +  
 geom_line(linetype = 2,  alpha = 0.6, size = 0.4, colour = inbo_grijsblauw)  + 
  facet_grid(soort_nl ~ jaar) +
  labs(x = "Datum bezoek", y = "Aantal getelde individuen") + 
  scale_x_date(date_breaks = "1 week", date_labels = "%d %b") +
  ylim(0, max_soort) + 
  theme(legend.position = 'none', axis.text.x = element_text(angle = 90))
  p #ggplotly(p) 
 
```



### Zadelsprinkhaan

```{r}
soort <- "Zadelsprinkhaan"

```

```{r Zadelsprinkhaangemiddeld, fig.cap= str_c("Evolutie gemiddelde getelde aantallen per bezoek: ", soort), fig.height= 3, fig.width= 4}

aantallen_soort <- aantallen_bezoek_totaal %>%
   filter(primaire_soort) %>%
   filter(meetnet == soort ) %>%
   mutate(doy_date = as.Date(doy, origin = "2016-01-01"))

aantallen_soort %>%
  ggplot(aes(x= jaar, y = aantal)) +  
  #geom_point(alpha = 0.6, colour = inbo.grijs) +
  stat_summary(fun.data = "mean_cl_boot", colour = inbo_rood, size = 1, alpha = 0.8) +
  facet_wrap(~ soort_nl, scale = "free_y") +
  labs(y = "Aantal getelde individuen", x = "Jaar") +
  theme(legend.position = "bottom") 

```

```{r Zadelsprinkhaan, fig.cap= str_c("Evolutie getelde individuen binnen telperiode: ", soort) , message=FALSE, warning= FALSE, fig.width= 8, fig.height= 3}



max_soort <- max(aantallen_soort$aantal) * 1.2

 p <- aantallen_soort %>%
  ggplot(aes(x = doy_date, 
             y = aantal,
             group= locatie, 
             colour = locatie)) + 
  geom_point(alpha = 0.6) +  
 geom_line(linetype = 2,  alpha = 0.6, size = 0.4, colour = inbo_grijsblauw)  + 
  facet_grid(soort_nl ~ jaar) +
  labs(x = "Datum bezoek", y = "Aantal getelde individuen") + 
  scale_x_date(date_breaks = "1 month", date_labels = "%b") +
  ylim(0, max_soort) + 
  theme(legend.position = 'none', axis.text.x = element_text(angle = 90))
  p #ggplotly(p) 
 
```




